# Generated by Django 5.0.6 on 2024-07-22 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0006_alter_product_provider"),
        ("core", "0008_alter_apikey_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique ID used internally to reference and identify claim objects",
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(
                        help_text="Claim Reference Number issued by insurer to identify and manage claim tracking process ",
                        max_length=50,
                        unique=True,
                        verbose_name="Claim Number",
                    ),
                ),
                (
                    "claim_date",
                    models.DateField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Date at which a claim is created",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("denied", "Rejected"),
                            ("paid", "Paid"),
                            ("offer_sent", "Offer sent"),
                            ("offer_accepted", "Offer accepted"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.policy"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.provider"
                    ),
                ),
            ],
            options={
                "verbose_name": "claim",
                "verbose_name_plural": "claims",
            },
        ),
        migrations.CreateModel(
            name="StatusTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("denied", "Rejected"),
                            ("paid", "Paid"),
                            ("offer_sent", "Offer sent"),
                            ("offer_accepted", "Offer accepted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_status_timeline",
                        to="claims.claim",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["created_at"], name="created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["claim_number"], name="claim_number_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["id"], name="claim_id_idx"),
        ),
    ]
