# Generated by Django 5.0.6 on 2024-08-13 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="estimated_loss",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="payout_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                            ("picture", "Picture"),
                        ],
                        help_text="Type of evidence uploaded.",
                        max_length=10,
                        verbose_name="Evidence Type",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Name of the document uploaded.",
                        max_length=255,
                        verbose_name="Document Name",
                    ),
                ),
                (
                    "blob",
                    models.CharField(
                        help_text="Reference to the stored document (e.g., Google Cloud Storage blob name).",
                        max_length=1024,
                        verbose_name="File Reference",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_documents",
                        to="claims.claim",
                        verbose_name="Related Claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Document",
                "verbose_name_plural": "Claim Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="documents",
            field=models.ManyToManyField(
                help_text="Documents uploaded by the policyholder as part of the claim",
                related_name="claims",
                to="claims.claimdocument",
                verbose_name="Documents",
            ),
        ),
    ]
