# Generated by Django 5.0.6 on 2024-08-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("claims", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.customer"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.policy"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.provider"
            ),
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_documents",
                to="claims.claim",
                verbose_name="Related Claim",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents uploaded by the policyholder as part of the claim",
                related_name="claims",
                to="claims.claimdocument",
                verbose_name="Documents",
            ),
        ),
        migrations.AddField(
            model_name="statustimeline",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_status_timeline",
                to="claims.claim",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["created_at"], name="created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["claim_number"], name="claim_number_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["id"], name="claim_id_idx"),
        ),
    ]
