# Generated by Django 5.0.6 on 2024-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "claims",
            "0002_claim_estimated_loss_claim_notes_claim_payout_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents uploaded by the policyholder as part of the claim",
                related_name="claims",
                to="claims.claimdocument",
                verbose_name="Documents",
            ),
        ),
    ]
