# Generated by Django 5.0.6 on 2024-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_alter_claim_documents"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="claim",
            options={
                "ordering": ["-claim_date", "-created_at"],
                "verbose_name": "claim",
                "verbose_name_plural": "claims",
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="incident_date",
            field=models.DateField(null=True, verbose_name="Date of Incident"),
        ),
    ]
