# Generated by Django 5.0.6 on 2024-09-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_alter_claim_customer"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="customer",
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("customer", "beneficiary")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_object_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="claimant_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("beneficiary", "Beneficiary")],
                default="customer",
                max_length=30,
            ),
        ),
    ]
