# Generated by Django 5.0.6 on 2024-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_alter_claim_options_claim_incident_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimdocument",
            name="blob",
        ),
        migrations.AddField(
            model_name="claimdocument",
            name="document_url",
            field=models.URLField(
                help_text="Reference to the stored document (e.g., Google Cloud Storage blob name).",
                max_length=1024,
                null=True,
                verbose_name="File Reference",
            ),
        ),
    ]
