# Generated by Django 5.0.6 on 2024-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0005_remove_claimdocument_blob_claimdocument_document_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="claim_type",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
