# Generated by Django 5.0.6 on 2024-08-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0006_claim_claim_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="incident_description",
            field=models.TextField(null=True),
        ),
    ]
