# Generated by Django 5.0.6 on 2024-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0007_claim_incident_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimWitness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text='Full name of the witness in the format, "First Name Last Name"',
                        max_length=100,
                    ),
                ),
                ("contact_phone", models.CharField()),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "statement",
                    models.CharField(
                        help_text="A brief statement from the witness about the incident",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
