# Generated by Django 5.0.6 on 2024-08-29 17:24

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        help_text="Unique key generated on the platform for use in subsequent request",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hashed value of the key shared with the merchant. Always use this and never use the actual `key` in requests.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "application_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "test_mode",
                    models.BooleanField(
                        help_text="Whether the application is in test mode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "coverage_name",
                    models.CharField(
                        help_text="Name of the coverage e.g collision, hospitalization, etc.",
                        max_length=100,
                        verbose_name="Coverage Name",
                    ),
                ),
                (
                    "coverage_id",
                    models.CharField(
                        help_text="unique identifier to track coverage details",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Coverage ID",
                    ),
                ),
                (
                    "coverage_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="This is the maximum amount that the insurance company will pay for a claim",
                        max_digits=10,
                        null=True,
                        verbose_name="Coverage Limit",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the coverage",
                        verbose_name="Description",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Given name as it appears on ID",
                        max_length=40,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="Middle name as it appears on User's ID ",
                        max_length=40,
                        null=True,
                        verbose_name="middle name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Family name as it appears on ID",
                        max_length=40,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Email", max_length=254, unique=True),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Physical address of the customer",
                        verbose_name="Address",
                    ),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates if the customer has completed KYC",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        help_text="Date of birth of the customer",
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number of the customer",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        help_text="Gender of the customer, identified as: M for Male, F for Female",
                        max_length=1,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        help_text="Type of verification document",
                        max_length=20,
                        null=True,
                        verbose_name="Verification Type",
                    ),
                ),
                (
                    "verification_id",
                    models.CharField(
                        help_text="ID of the verification document",
                        max_length=20,
                        null=True,
                        verbose_name="Verification ID",
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=True,
                        help_text="Designates if the user is a staff member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the provider",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Insurance Provider. This could be a short form of the company name",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address is used to track their support team during integrations",
                        max_length=254,
                        null=True,
                        verbose_name="Business email",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the insurance provider's support team",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurer",
                "verbose_name_plural": "Insurers",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID of the user",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Given name as it appears on ID",
                        max_length=150,
                        null=True,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Family name as it appears on ID",
                        max_length=150,
                        null=True,
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("merchant", "Merchant"),
                            ("support", "Customer Support"),
                        ],
                        default="support",
                        help_text="Designates the role of a given user on the platform",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name", "last_login", "date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=True)),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=True, help_text="Designates if the user is a superuser"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
