# Generated by Django 5.0.6 on 2024-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Designates the username of a given user",
                null=True,
                unique=True,
            ),
        ),
    ]
