# Generated by Django 5.0.6 on 2024-06-20 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_trashed", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "policy_id",
                    models.BigAutoField(
                        help_text="Unique identifier for the package",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Name of the package offered by the insurance provider",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the package"),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("Life", "Life Insurance"),
                            ("Health", "Health Insurance"),
                            ("Auto", "Auto Insurance"),
                            ("Gadget", "Gadget Insurance"),
                            ("Travel", "Travel Insurance"),
                        ],
                        help_text="Type of insurance package",
                        max_length=15,
                    ),
                ),
                (
                    "coverage_details",
                    models.TextField(help_text="Detailed breakdown of what's covered"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price of the package prior to any modifications or adjustments",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the provider",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Insurance Provider. This could be a short form of the company name",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        help_text="This is used in the system to identify the provider. It should be unique, example includes: AXA-XXXX, HEIR-XXXX, UNYT-XXXX, LEAD-XXXX, etc.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "tax_identification_number",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="TIN"
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address is used to track their support team during integrations",
                        max_length=254,
                        null=True,
                        verbose_name="Business email",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coverage_name",
                    models.CharField(
                        help_text="Name of the coverage e.g collision, hospitalization, etc.",
                        max_length=100,
                        verbose_name="Coverage Name",
                    ),
                ),
                (
                    "coverage_id",
                    models.CharField(
                        help_text="unique identifier to track coverage details",
                        max_length=100,
                        verbose_name="Coverage ID",
                    ),
                ),
                (
                    "coverage_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="This is the maximum amount that the insurance company will pay for a claim",
                        max_digits=10,
                        verbose_name="Coverage Limit",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the coverage",
                        verbose_name="Description",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        help_text="Product to which the coverage belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="core.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                help_text="Insurance provider offering the package",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.provider",
            ),
        ),
    ]
