# Generated by Django 5.0.6 on 2024-08-29 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("core", "0001_initial"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="api_key",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.apikey",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="merchants.merchant"
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="product",
            field=models.ForeignKey(
                help_text="Product to which the coverage belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                help_text="Merchant that created the customer",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="customersupport",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["first_name", "last_name"], name="core_user_first_n_7ed624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["first_name", "last_name", "email"],
                name="core_custom_first_n_3f986d_idx",
            ),
        ),
    ]
