# Generated by Django 5.0.6 on 2024-07-01 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_username"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_trashed", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "policy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for the policy",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="Date the policy was purchased"),
                ),
                (
                    "effective_through",
                    models.DateField(help_text="Date the policy expires"),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid for the policy",
                        max_digits=10,
                    ),
                ),
                (
                    "renewable",
                    models.BooleanField(
                        default=False, help_text="Indicates if the policy is renewable"
                    ),
                ),
                (
                    "inspection_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if an inspection is required before the policy can be purchased",
                    ),
                ),
                (
                    "cerfication_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if any certifications are required before the policy can be purchased",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="policy_id",
        ),
        migrations.AddField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for the package",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_live",
            field=models.BooleanField(
                default=True, help_text="Indicates if the package is live"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="support_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number of the insurance provider's support team",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                help_text="Insurance provider offering the package",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.provider",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="core_produc_name_be3252_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type"], name="core_produc_product_3906a7_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
        migrations.AddField(
            model_name="policy",
            name="coverage",
            field=models.ForeignKey(
                help_text="Coverage details for the policy",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.coverage",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="merchant_id",
            field=models.ForeignKey(
                help_text="Merchant who sold the policy",
                on_delete=django.db.models.deletion.CASCADE,
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_holder",
            field=models.ForeignKey(
                help_text="User who purchased the policy",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="product",
            field=models.ForeignKey(
                help_text="Insurance package purchased by the user",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="provider_id",
            field=models.ForeignKey(
                help_text="Insurance provider for the policy",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.provider",
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["effective_from", "effective_through", "policy_id", "premium"],
                name="core_policy_effecti_37e3aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_holder"], name="core_policy_policy__f11448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["provider_id"], name="core_policy_provide_c01d5c_idx"
            ),
        ),
    ]
