# Generated by Django 5.0.6 on 2024-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products offered by the provider",
                related_name="providers",
                to="catalog.product",
            ),
        ),
    ]
