# Generated by Django 5.0.6 on 2024-07-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0003_policy_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="provider",
        ),
        migrations.AlterField(
            model_name="coverage",
            name="product_id",
            field=models.ForeignKey(
                help_text="Product to which the coverage belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="catalog.product",
            ),
        ),
        migrations.DeleteModel(
            name="Policy",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
