# Generated by Django 5.0.6 on 2024-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_provider_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coverage",
            options={"verbose_name": "Coverage", "verbose_name_plural": "Coverages"},
        ),
        migrations.AddField(
            model_name="coverage",
            name="benefits",
            field=models.TextField(
                blank=True,
                help_text="Specific benefits included in the coverage",
                null=True,
                verbose_name="Benefits",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="coverage_period_end",
            field=models.DateField(
                blank=True,
                help_text="End date of the coverage period",
                null=True,
                verbose_name="Coverage End Date",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="exclusions",
            field=models.TextField(
                blank=True,
                help_text="Exclusions or limitations of the coverage",
                null=True,
                verbose_name="Exclusions",
            ),
        ),
        migrations.AlterField(
            model_name="coverage",
            name="coverage_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="This is the maximum amount that the insurance company will pay for a claim",
                max_digits=10,
                null=True,
                verbose_name="Coverage Limit",
            ),
        ),
    ]
