# Generated by Django 5.0.6 on 2024-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_coverage_options_coverage_benefits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverage",
            name="product",
        ),
        migrations.AddField(
            model_name="coverage",
            name="currency",
            field=models.CharField(
                default="NGN",
                help_text="Currency of the coverage limit, e.g., USD, EUR",
                max_length=10,
                verbose_name="Currency",
            ),
        ),
    ]
