# Generated by Django 5.0.6 on 2024-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_product_provider_alter_coverage_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("merchant_admin", "Merchant Admin"),
                    ("admin", "Admin"),
                    ("support", "Customer Support"),
                ],
                default="merchant_admin",
                help_text="Designates the role of a given user on the platform",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
