# Generated by Django 5.0.6 on 2024-07-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_role"),
        (
            "merchants",
            "0002_alter_merchant_is_active_alter_merchant_short_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="api_token",
        ),
        migrations.RemoveField(
            model_name="application",
            name="id",
        ),
        migrations.AddField(
            model_name="application",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="application_id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("support", "Customer Support")],
                default="admin",
                help_text="Designates the role of a given user on the platform",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="merchants.merchant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="api_key",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.apikey",
            ),
        ),
    ]
