# Generated by Django 5.0.6 on 2024-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_coverage_product_coverage_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverage",
            name="coverage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Medical", "Medical Coverage"),
                    ("Collision", "Collision Coverage"),
                    ("Liability", "Liability Coverage"),
                    ("Property", "Property Coverage"),
                    ("Travel", "Travel Coverage"),
                    ("Accidental", "Accidental Coverage"),
                    ("Other", "Other Coverage"),
                ],
                help_text="Internal recognized of coverages",
                null=True,
            ),
        ),
    ]
