# Generated by Django 5.0.6 on 2024-07-17 15:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_application_api_token_remove_application_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="key",
        ),
        migrations.AddField(
            model_name="apikey",
            name="hashed_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="api_key",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.apikey",
            ),
        ),
    ]
