# Generated by Django 5.0.6 on 2024-10-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_coverage_coverage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="is_internal",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the provider is an internal provider or not - that is if the provider does not have an API",
            ),
        ),
    ]
