# Generated by Django 5.0.6 on 2024-07-17 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_apikey_key_apikey_hashed_key_alter_apikey_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
