# Generated by Django 5.1.2 on 2024-10-23 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_provider_is_internal"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="merchant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="merchants.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="application_id",
            field=models.CharField(
                default="82e1e912-c5a8-41bb-8a9c-253894e62670",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="merchants.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="test_mode",
            field=models.BooleanField(
                default=True,
                help_text="True if the application is in test mode (sandbox), otherwise false for production.",
            ),
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the client or environment (merchant ID or internal client ID).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for the environment.",
                        max_length=255,
                    ),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the environment is in test mode (sandbox) or production.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="merchants.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIKeyV2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hashed value of the API key. The raw key is never stored due to compliance and security reasons.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "api_key_type",
                    models.CharField(
                        choices=[
                            ("merchant", "Merchant"),
                            ("internal", "Internal Backend"),
                        ],
                        help_text="Type of API key: 'merchant' for merchant integrations or 'internal' for backend use.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the key is active. Utilized for revoking access.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        help_text="The environment associated with this API key.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="core.environment",
                    ),
                ),
            ],
        ),
    ]
