# Generated by Django 5.0.6 on 2024-07-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_apikey_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="short_code",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="tax_identification_number",
        ),
    ]
