# Generated by Django 5.1.2 on 2024-10-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_apikey_merchant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikeyv2",
            name="client_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique identifier for the client or environment (merchant ID or internal client ID).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="apikeyv2",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                help_text="The environment associated with this API key.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="core.environment",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="application_id",
            field=models.CharField(
                default="0c814e0d-3303-4600-a393-533494772049",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="client_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier for the merchant client.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
