# Generated by Django 5.0.6 on 2024-08-06 16:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_provider_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverage",
            name="coverage_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="This is the maximum amount that the insurance company will pay for a claim",
                max_digits=10,
                verbose_name="Coverage Limit",
            ),
        ),
    ]
