# Generated by Django 5.0.6 on 2024-08-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_provider_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("merchant", "Merchant"),
                    ("support", "Customer Support"),
                ],
                default="admin",
                help_text="Designates the role of a given user on the platform",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
