# Generated by Django 5.0.6 on 2024-08-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Given name as it appears on ID",
                max_length=40,
                null=True,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Family name as it appears on ID",
                max_length=40,
                null=True,
                verbose_name="Last Name",
            ),
        ),
    ]
