# Generated by Django 5.0.6 on 2024-08-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_coverage_coverage_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coverage",
            old_name="product_id",
            new_name="product",
        ),
    ]
