# Generated by Django 5.0.6 on 2024-08-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_rename_product_id_coverage_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverage",
            name="id",
        ),
        migrations.AlterField(
            model_name="coverage",
            name="coverage_id",
            field=models.CharField(
                help_text="unique identifier to track coverage details",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Coverage ID",
            ),
        ),
        migrations.AlterField(
            model_name="coverage",
            name="coverage_limit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="This is the maximum amount that the insurance company will pay for a claim",
                max_digits=10,
                null=True,
                verbose_name="Coverage Limit",
            ),
        ),
    ]
