# Generated by Django 5.0.6 on 2024-08-05 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_first_name_alter_user_last_name"),
        (
            "merchants",
            "0002_alter_merchant_is_active_alter_merchant_short_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                help_text="Merchant that created the customer",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="merchants.merchant",
            ),
        ),
    ]
