# Generated by Django 5.0.6 on 2024-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_coverage_id_alter_coverage_coverage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="dob",
            field=models.DateField(
                help_text="Date of birth of the customer",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                help_text="Gender of the customer, identified as: M for Male, F for Female",
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="verification_id",
            field=models.CharField(
                help_text="ID of the verification document",
                max_length=20,
                null=True,
                verbose_name="Verification ID",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="verification_type",
            field=models.CharField(
                help_text="Type of verification document",
                max_length=20,
                null=True,
                verbose_name="Verification Type",
            ),
        ),
    ]
