# Generated by Django 5.0.6 on 2024-08-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_admin_customersupport"),
        ("core", "0014_alter_customer_dob_alter_customer_gender_and_more"),
    ]

    operations = []
