# Generated by Django 5.0.6 on 2024-08-15 10:34

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_merge_20240815_1029"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="is_admin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_superuser",
            field=models.BooleanField(
                default=True, help_text="Designates if the user is a superuser"
            ),
        ),
        migrations.AddField(
            model_name="customersupport",
            name="is_staff",
            field=models.BooleanField(
                default=True, help_text="Designates if the user is a staff member"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Given name as it appears on ID",
                max_length=150,
                null=True,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Family name as it appears on ID",
                max_length=150,
                null=True,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
