# Generated by Django 5.0.6 on 2024-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_admin_is_admin_admin_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
