# Generated by Django 5.0.6 on 2024-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("merchant", "Merchant"),
                    ("support", "Customer Support"),
                ],
                default="support",
                help_text="Designates the role of a given user on the platform",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
