# Generated by Django 5.0.6 on 2024-08-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_switch_to_uuid_id"),
        ("core", "0020_alter_user_email_alter_user_username"),
    ]

    operations = []
