# Generated by Django 5.0.6 on 2024-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_apikey_id"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="apikey",
        #     name="key",
        #     field=models.CharField(
        #         default="default_key",
        #         help_text="Unique key generated on the platform for use in subsequent request",
        #         max_length=150,
        #         unique=True,
        #     ),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(
                default="default_hash_key",
                help_text="Hashed value of the key shared with the merchant. Always use this and never use the actual `key` in requests.",
                max_length=150,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
