steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/superpool-api", "."]

  # Push Image to Google's Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "Push image to Artifact Registry"
    args: ["push", "gcr.io/$PROJECT_ID/superpool-api"]

  # Ship App Image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Ship app image to Cloud Run"
    args:
      - "run"
      - "deploy"
      - "superpool-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/superpool-api"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"

  # Ship Celery to Cloud Run
   - name: "gcr.io/cloud-builders/gcloud"
     id: "ship celery"
     args:
      - "run"
      - "deploy"
      - "superpool-celery-worker"
      - "--image"
      - "gcr.io/$PROJECT_ID/superpool-api"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "APP_COMMAND=celery -A superpool.api.celery worker --loglevel=info"
      - "--port"
      - "8080"
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "run"
  #     - "deploy"
  #     - "superpool-celery-worker"
  #     - "--image"
  #     - "gcr.io/$PROJECT_ID/superpool-api"
  #     - "--platform"
  #     - "managed"
  #     - "--region"
  #     - "us-central1"
  #     - "--allow-unauthenticated"
  #     - "--command"
  #     - "celery"
  #     - "--args"
  #     - "-A celery_app worker --loglevel=info"
      # - "--port"
      # - "8080"

  # Deploy Flower on Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Deploy Flower"
    args:
      - "run"
      - "deploy"
      - "superpool-flower"
      - "--image"
      - "gcr.io/$PROJECT_ID/superpool-api"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--command"
      - "celery"
      - "--args"
      - "-A celery_app flower --port=8080"
      # - "--port"
      # - "8080" #"5555"

images:
  - "gcr.io/$PROJECT_ID/superpool-api"

options:
  logging: CLOUD_LOGGING_ONLY
