# Generated by Django 5.0.6 on 2024-07-01 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_policy_alter_product_options_and_more"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_trashed", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for the package",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the package offered by the insurance provider",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the package"),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("Life", "Life Insurance"),
                            ("Health", "Health Insurance"),
                            ("Auto", "Auto Insurance"),
                            ("Gadget", "Gadget Insurance"),
                            ("Travel", "Travel Insurance"),
                        ],
                        help_text="Type of insurance package",
                        max_length=15,
                    ),
                ),
                (
                    "coverage_details",
                    models.TextField(help_text="Detailed breakdown of what's covered"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price of the package prior to any modifications or adjustments",
                        max_digits=10,
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=True, help_text="Indicates if the package is live"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Insurance provider offering the package",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_trashed", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "policy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for the policy",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="Date the policy was purchased"),
                ),
                (
                    "effective_through",
                    models.DateField(help_text="Date the policy expires"),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid for the policy",
                        max_digits=10,
                    ),
                ),
                (
                    "renewable",
                    models.BooleanField(
                        default=False, help_text="Indicates if the policy is renewable"
                    ),
                ),
                (
                    "inspection_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if an inspection is required before the policy can be purchased",
                    ),
                ),
                (
                    "cerfication_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if any certifications are required before the policy can be purchased",
                    ),
                ),
                (
                    "coverage",
                    models.ForeignKey(
                        help_text="Coverage details for the policy",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.coverage",
                    ),
                ),
                (
                    "merchant_id",
                    models.ForeignKey(
                        help_text="Merchant who sold the policy",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.merchant",
                    ),
                ),
                (
                    "policy_holder",
                    models.ForeignKey(
                        help_text="User who purchased the policy",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                    ),
                ),
                (
                    "provider_id",
                    models.ForeignKey(
                        help_text="Insurance provider for the policy",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.provider",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Insurance package purchased by the user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type"], name="catalog_pro_product_9ecdd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["effective_from", "effective_through", "policy_id", "premium"],
                name="catalog_pol_effecti_11fbed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_holder"], name="catalog_pol_policy__3c29a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["provider_id"], name="catalog_pol_provide_90772d_idx"
            ),
        ),
    ]
