# Generated by Django 5.0.6 on 2024-08-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="coverage",
            field=models.ForeignKey(
                help_text="Coverage details for the policy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.coverage",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="merchant",
            field=models.ForeignKey(
                help_text="Merchant who sold the policy",
                on_delete=django.db.models.deletion.CASCADE,
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_holder",
            field=models.ForeignKey(
                help_text="User who purchased the policy",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="provider_id",
            field=models.ForeignKey(
                help_text="Insurance provider for the policy",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.provider",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                help_text="Insurance provider offering the package",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.provider",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="product",
            field=models.ForeignKey(
                help_text="Insurance package purchased by the user",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="premium",
            field=models.ForeignKey(
                help_text="The calculated premium for the quote",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.price",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="product",
            field=models.ForeignKey(
                help_text="Insurance Product/Service covered by the quote",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type"], name="catalog_pro_product_9ecdd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["effective_from", "effective_through", "policy_id", "premium"],
                name="catalog_pol_effecti_11fbed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_holder"], name="catalog_pol_policy__3c29a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["provider_id"], name="catalog_pol_provide_90772d_idx"
            ),
        ),
    ]
