# Generated by Django 5.0.6 on 2024-07-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="effective_from",
            field=models.DateField(
                blank=True, help_text="Date the policy was purchased"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="effective_through",
            field=models.DateField(blank=True, help_text="Date the policy expires"),
        ),
        migrations.AlterField(
            model_name="product",
            name="coverage_details",
            field=models.TextField(
                help_text="Detailed breakdown of what's covered", null=True
            ),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=14, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_quote",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "quote",
                "verbose_name_plural": "quotes",
            },
        ),
    ]
