# Generated by Django 5.0.6 on 2024-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_policy_effective_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="product",
        ),
        migrations.AlterField(
            model_name="policy",
            name="effective_from",
            field=models.DateField(help_text="Date the policy was purchased"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="effective_through",
            field=models.DateField(help_text="Date the policy expires"),
        ),
        migrations.AlterField(
            model_name="product",
            name="coverage_details",
            field=models.TextField(
                blank=True, help_text="Detailed breakdown of what's covered", null=True
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=80,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
