# Generated by Django 5.0.6 on 2024-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_product_type"),
        ("core", "0005_remove_coverage_product_coverage_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="coverage_details",
        ),
        migrations.AddField(
            model_name="product",
            name="coverages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Detailed breakdown of what's covered",
                to="core.coverage",
            ),
        ),
    ]
