# Generated by Django 5.0.6 on 2024-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_coverage_details_product_coverages"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="currency",
            field=models.CharField(
                default="NGN", help_text="Currency code", max_length=3
            ),
        ),
    ]
