# Generated by Django 5.0.6 on 2024-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_quote_product_alter_policy_effective_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Name of the package offered by the insurance provider",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Life", "Life Insurance"),
                    ("Health", "Health Insurance"),
                    ("Auto", "Auto Insurance"),
                    ("Gadget", "Gadget Insurance"),
                    ("Travel", "Travel Insurance"),
                ],
                help_text="Type of insurance package",
                max_length=255,
            ),
        ),
    ]
