# Generated by Django 5.0.6 on 2024-07-22 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_name_alter_product_product_type"),
        ("core", "0008_alter_apikey_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                help_text="Insurance provider offering the package",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.provider",
            ),
        ),
    ]
