# Generated by Django 5.0.6 on 2024-08-29 23:13

import core.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_price_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="expires_in",
            field=models.DateTimeField(
                default=core.catalog.models.default_expiry_date,
                help_text="The expiry date of the quote.",
            ),
        ),
    ]
