# Generated by Django 5.0.6 on 2024-07-25 10:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "comission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "surcharges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="quote",
            name="id",
        ),
        migrations.AddField(
            model_name="quote",
            name="expires_in",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 7, 25, 10, 42, 14, 649528),
                help_text="The expiry date of the quote.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="product",
            field=models.ForeignKey(
                default=1,
                help_text="Insurance Product/Service covered by the quote",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="quote_code",
            field=models.CharField(
                default="quo_XXxx_xxxxxxx",
                editable=False,
                help_text="Assigned identifier for managing quote objects",
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Quote Code",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("accepted", "accepted"),
                    ("declined", "declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of quote excluding  discount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="premium",
            field=models.ForeignKey(
                default=1,
                help_text="The calculated premium for the quote",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.price",
            ),
            preserve_default=False,
        ),
    ]
