# Generated by Django 5.0.6 on 2024-09-16 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_policy_policy_holder"),
        ("core", "0005_remove_coverage_product_coverage_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Monthly", "Monthly"),
                    ("Annual", "Annual"),
                    ("Quarterly", "Quarterly"),
                ],
                default="Monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="pricing_model",
            field=models.CharField(
                choices=[
                    ("Flat", "Flat Rate"),
                    ("Fixed", "Fixed Rate"),
                    ("Dynamic", "Dynamic Rate"),
                ],
                default="Fixed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProductTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic Insurance"),
                            ("Advanced", "Advanced"),
                            ("Standard", "Standard Insurance"),
                            ("Premium", "Premium"),
                            ("Bronze", "Bronze"),
                            ("Silver", "Silver"),
                            ("Other", "Other"),
                        ],
                        help_text="Name of the product tier",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional - description of the product tier",
                        null=True,
                    ),
                ),
                (
                    "base_preimum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price for the product tier",
                        max_digits=10,
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True,
                        help_text="Specific benefits included in the coverage",
                        null=True,
                        verbose_name="Benefits",
                    ),
                ),
                (
                    "exclusions",
                    models.TextField(
                        blank=True,
                        help_text="Exclusions or limitations of the coverage",
                        null=True,
                        verbose_name="Exclusions",
                    ),
                ),
                (
                    "coverages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Detailed breakdown of what's covered",
                        to="core.coverage",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pricing for the product tier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.price",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Insurance package the tier belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        related_query_name="tier",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "tier_name")},
            },
        ),
    ]
