# Generated by Django 5.0.6 on 2024-09-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_price_frequency_price_pricing_model_producttier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="pricing_model",
            field=models.CharField(
                choices=[("Fixed", "Fixed Rate"), ("Dynamic", "Dynamic Rate")],
                default="Fixed",
                max_length=20,
            ),
        ),
    ]
