# Generated by Django 5.0.6 on 2024-07-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_rename_base_price_price_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="policy_number",
            field=models.CharField(
                blank=True,
                help_text="Policy Refrence Number assigned by the insurer e.g GI86585700-1, AXA2024727-2, LEAD18002-42, etc",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="renewal_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when this insurance policy is due for renewal",
                null=True,
            ),
        ),
    ]
