# Generated by Django 5.0.6 on 2024-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_policy_policy_number_policy_renewal_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="cancellation_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when the policy was cancelled", null=True
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="cancellation_initiator",
            field=models.CharField(
                blank=True,
                help_text="Who requested for cancellation of this policy?",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, help_text="Reason for policy cancellation", null=True
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[("accepted", "Accepted"), ("cancelled", "Cancelled")],
                default="active",
                help_text="Current status of the policy",
                max_length=20,
            ),
        ),
    ]
