# Generated by Django 5.0.6 on 2024-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_price_pricing_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Life", "Life Insurance"),
                    ("Health", "Health Insurance"),
                    ("Auto", "Auto Insurance"),
                    ("Gadget", "Gadget Insurance"),
                    ("Travel", "Travel Insurance"),
                    ("Home", "Home Insurance"),
                    ("Student_Protection", "Student Protection"),
                    ("Personal_Accident", "Personal Accident Insurance"),
                    ("CreditLife", "Credit Life Insurance"),
                    ("PetCare", "PetCare Insurance"),
                    ("Other", "Other"),
                ],
                help_text="Type of insurance package",
                max_length=255,
            ),
        ),
    ]
