# Generated by Django 5.0.6 on 2024-09-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttier",
            name="tier_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic Insurance"),
                    ("Advanced", "Advanced"),
                    ("Standard", "Standard Insurance"),
                    ("Premium", "Premium"),
                    ("Bronze", "Bronze"),
                    ("Silver", "Silver"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttier",
            name="tier_name",
            field=models.CharField(
                help_text="Name of the product tier", max_length=255
            ),
        ),
    ]
