# Generated by Django 5.0.6 on 2024-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_rename_value_price_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="additional_metadata",
            field=models.JSONField(
                blank=True,
                help_text="Additional information about the quote",
                null=True,
            ),
        ),
    ]
