# Generated by Django 5.0.6 on 2024-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_quote_additional_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Life", "Life Insurance"),
                    ("Health", "Health Insurance"),
                    ("Auto", "Auto Insurance"),
                    ("Gadget", "Gadget Insurance"),
                    ("Travel", "Travel Insurance"),
                    ("Home", "Home Insurance"),
                ],
                help_text="Type of insurance package",
                max_length=255,
            ),
        ),
    ]
