# Generated by Django 5.0.6 on 2024-09-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_quote_purchase_id_quote_purchase_id_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttier",
            old_name="base_preimum",
            new_name="base_premium",
        ),
        migrations.AlterField(
            model_name="producttier",
            name="tier_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic Insurance"),
                    ("Advanced", "Advanced"),
                    ("Standard", "Standard Insurance"),
                    ("Premium", "Premium"),
                    ("Bronze", "Bronze"),
                    ("Silver", "Silver"),
                    ("Comprehensive", "Comprehensive"),
                    ("ThirdParty", "ThirdParty"),
                    ("Other", "Other"),
                ],
                help_text="Type of tier. Choose from predefined options such as Basic, Premium, Silver, Corporate, Comprehensive, etc. An optional classification that further categorizes the tier",
                max_length=255,
                null=True,
            ),
        ),
    ]
