# Generated by Django 5.0.6 on 2024-08-07 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_product_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the package",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
