# Generated by Django 5.0.6 on 2024-08-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_product_id"),
        ("core", "0013_remove_coverage_id_alter_coverage_coverage_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="coverage",
            field=models.ForeignKey(
                help_text="Coverage details for the policy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.coverage",
            ),
        ),
    ]
