# Generated by Django 5.0.6 on 2024-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_quote_policy_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="policy_terms",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Terms and conditions of the insurance policy, stored as a JSON object.",
            ),
        ),
    ]
