# Generated by Django 5.0.6 on 2024-10-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_quote_policy_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="origin",
            field=models.CharField(
                choices=[("Internal", "Internal"), ("External", "External")],
                default="Internal",
                help_text="The origin of the quote, e.g., Internal, or External provider",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Life", "Life Insurance"),
                    ("Health", "Health Insurance"),
                    ("Auto", "Auto Insurance"),
                    ("Gadget", "Gadget Insurance"),
                    ("Travel", "Travel Insurance"),
                    ("Home", "Home Insurance"),
                    ("Student_Protection", "Student Protection"),
                    ("Accident", "Accident Insurance"),
                    ("Personal_Accident", "Personal Accident Insurance"),
                    ("CreditLife", "Credit Life Insurance"),
                    ("PetCare", "PetCare Insurance"),
                    ("General", "General Insurance"),
                    ("Other", "Other"),
                ],
                help_text="Type of insurance package",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
