# Generated by Django 5.0.6 on 2024-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_rename_merchant_id_policy_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                    ("active", "Active"),
                ],
                default="active",
                help_text="Current status of the policy",
                max_length=20,
            ),
        ),
    ]
