# Generated by Django 5.0.6 on 2024-10-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_quote_origin_alter_product_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="The provider of the quote, e.g., AXA, Leadway, etc",
                max_length=255,
                null=True,
            ),
        ),
    ]
