# Generated by Django 5.0.6 on 2024-10-07 16:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_quote_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_premium",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Base premium price if no tiers are defined",
                max_digits=10,
            ),
        ),
    ]
