# Generated by Django 5.0.6 on 2024-08-13 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_policy_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("middle_name", models.CharField(blank=True, max_length=40, null=True)),
                ("last_name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField(null=True)),
                (
                    "relationship",
                    models.CharField(
                        help_text="Relationship to the policy holder", max_length=40
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Date of birth of the beneficiary", null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="policy",
            name="beneficiaries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Beneficiaries of this policy",
                related_name="beneficiaries",
                to="catalog.beneficiary",
                verbose_name="Beneficiaries",
            ),
        ),
    ]
