# Generated by Django 5.0.6 on 2024-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_product_base_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Life", "Life Insurance"),
                    ("Health", "Health Insurance"),
                    ("Auto", "Auto Insurance"),
                    ("Cargo", "Cargo (Shipment) Insurance"),
                    ("Gadget", "Gadget Insurance"),
                    ("Travel", "Travel Insurance"),
                    ("Home", "Home Insurance"),
                    ("Student_Protection", "Student Protection"),
                    ("Accident", "Accident Insurance"),
                    ("Personal_Accident", "Personal Accident Insurance"),
                    ("CreditLife", "Credit Life Insurance"),
                    ("PetCare", "PetCare Insurance"),
                    ("General", "General Insurance"),
                    ("Other", "Other"),
                ],
                help_text="Type of insurance package",
                max_length=255,
            ),
        ),
    ]
