# Generated by Django 5.1.2 on 2024-10-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_alter_product_product_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("amount", "description")},
        ),
    ]
