# Generated by Django 5.0.6 on 2024-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="The name of the business",
                        max_length=255,
                        verbose_name="Business Name",
                    ),
                ),
                (
                    "internal_id",
                    models.CharField(
                        help_text="Unique short code indentifier used internally to identify a merchant or distributor",
                        max_length=40,
                        unique=True,
                        verbose_name="Internal ID",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        help_text="The contact email address of the business",
                        max_length=254,
                        verbose_name="Business Email",
                    ),
                ),
                (
                    "tax_identification_number",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="TIN",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Registration Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
            },
        ),
    ]
