# Generated by Django 5.0.6 on 2024-06-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_trashed", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the business",
                        max_length=255,
                        verbose_name="Business Name",
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        help_text="Unique short code indentifier used internally to identify a merchant or distributore.g. UBA-X224, GTB-3X2, KON-001, SLOT-001, WEMA-2286, etc.",
                        max_length=10,
                        unique=True,
                        verbose_name="Merchant Short code",
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        blank=True,
                        help_text="Company registration email address",
                        max_length=254,
                        null=True,
                        verbose_name="Business Email",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        help_text="The contact email address of the business, for support if any",
                        max_length=254,
                        verbose_name="Support Email",
                    ),
                ),
                ("is_active", models.BooleanField()),
                (
                    "tax_identification_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique tax identification number issued by federal or inland revenue service",
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="TIN",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Government-issued registration number with the CAC",
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="The physical address of the business",
                        null=True,
                        verbose_name="Business Address",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="Unique key generated on the platform for use in subsequent request",
                        max_length=80,
                        null=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Designates if the business has been verified by the platform",
                        verbose_name="KYC Verified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
            },
        ),
    ]
