# Generated by Django 5.0.6 on 2024-06-28 09:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merchant",
            old_name="business_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="internal_id",
        ),
        migrations.AddField(
            model_name="merchant",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="The physical address of the business",
                null=True,
                verbose_name="Business Address",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="api_key",
            field=models.CharField(
                help_text="Unique key generated on the platform for use in subsequent request",
                max_length=80,
                null=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="business_email",
            field=models.EmailField(
                blank=True,
                help_text="Company registration email address",
                max_length=254,
                verbose_name="Business Email",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="merchant",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Designates if the merchant is active"
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="is_trashed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchant",
            name="kyc_verified",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Designates if the business has been verified by the platform",
                verbose_name="KYC Verified",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchant",
            name="short_code",
            field=models.CharField(
                help_text="Unique short code indentifier used internally to identify a merchant or distributore.g. UBA-X224, GTB-3X2, KON-001, SLOT-001, WEMA-2286, etc.",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Merchant Short code",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="trashed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Merchant ID",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Government-issued registration number with the CAC",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Registration Number",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="support_email",
            field=models.EmailField(
                blank=True,
                help_text="The contact email address of the business, for support if any",
                max_length=254,
                null=True,
                verbose_name="Support Email",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="tax_identification_number",
            field=models.CharField(
                blank=True,
                help_text="Unique tax identification number issued by federal or inland revenue service",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="TIN",
            ),
        ),
    ]
