# Generated by Django 5.0.6 on 2024-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "merchants",
            "0002_alter_merchant_is_active_alter_merchant_short_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates if the merchant is verified",
                null=True,
            ),
        ),
    ]
