# Generated by Django 5.0.6 on 2024-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_merchant_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Unique token generated for email verification",
                max_length=6,
                null=True,
                verbose_name="Verification Token",
            ),
        ),
        migrations.AddField(
            model_name="merchant",
            name="token_expires_at",
            field=models.DateTimeField(
                help_text="The date and time the verification token expires", null=True
            ),
        ),
    ]
