# Generated by Django 5.0.6 on 2024-08-14 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0004_merchant_token_merchant_token_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="tenant_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the merchant in the system",
                null=True,
                verbose_name="Tenant ID",
            ),
        ),
    ]
