# Generated by Django 5.0.6 on 2024-08-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_merchant_user"),
        ("merchants", "0005_merchant_tenant_id"),
    ]

    operations = []
