# Generated by Django 5.0.6 on 2024-08-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0006_merge_0003_merchant_user_0005_merchant_tenant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="api_key",
        ),
    ]
