# Property of Unyte Africa
#
# This file is used to define the container services that will be run in the local environment

service:
  test_database:
    image: postgres:16.3-alpine
    container_name: superpool_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-superpool}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crack_me_if_you_can}
    ports:
      - 5432:5432
    volumes:
      - ./superpool_test_database:/var/lib/postgresql/data:rw

  cache:
    image: redis:6.2-alpine
    container_name: superpool_redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data:rw

  # CELERY (CELERY AND CELERY FLOWER)
  worker:
    build:
      context: ./superpool/api
      dockerfile: ../Dockerfile
    container_name: jobberman
    command: celery -A superpool.api.tasks worker --pool=prefork --concurrency=4
    depends_on:
      - cache
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DATABASE_URL: ${DATABASE_URL}

  flower:
    image: celery/flower
    container_name: flower
    command: flower -A superppool.api.tasks --port=5555
    depends_on:
      - worker
    ports:
      - 5555:5555

volumes:
  superpool_test_database: {}
  redis_data: {}
