# Property of Unyte Africa
#
# This file is used to define the container services that will be run in the local environment

service:
  database:
    image: postgres:16.3-alpine
    container_name: superpool_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-superpool}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crack_me_if_you_can}
    ports:
      - 5432:5432
    volumes:
      - ./superpool_database:/var/lib/postgresql/data:rw
  redis:
    image: redis:6.2-alpine
    container_name: superpool_redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data:rw

volumes:
  superpool_database: {}
  redis_data: {}
